import type { Metadata } from "next";
import localFont from "next/font/local"; // Import local font module
import "./globals.css";
import Chatbot from "@/components/Chatbot";
import { Toaster } from "react-hot-toast";

// Load CanelaDeck fonts
const canelaDeck = localFont({
  src: [
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-BlackItalic.otf",
      weight: "900",
      style: "italic",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-LightItalic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/CanelaDeck/CanelaDeck-ThinItalic.otf",
      weight: "100",
      style: "italic",
    },
  ],
  variable: "--font-canela-deck", // Define a CSS variable for CanelaDeck
});

// Load GT-America fonts
const gtAmerica = localFont({
  src: [
    {
      path: "../../public/fonts/GT-America/GT-America-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Regular-Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Bold-Italic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Light-Italic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Medium-Italic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Thin-Italic.otf",
      weight: "100",
      style: "italic",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Ultra-Light.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/GT-America/GT-America-Ultra-Light-Italic.otf",
      weight: "200",
      style: "italic",
    },
  ],
  variable: "--font-gt-america", // Define a CSS variable for GT-America
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${canelaDeck.variable} ${gtAmerica.variable} antialiased`}
      >
              <Toaster />

        {children}
        <Chatbot />
      </body>
    </html>
  );
}
